- id: 100
  id_no: 10000
  category: 0
  name: 'Home'
  link: '' 
  active: true 
  note: 

- id: 200 
  id_no: 20000
  category: 0
  name: 'Services'
  link: '' 
  active: true
  note: 

- id: 201 
  id_no: 20000
  category: 'Services'
  name: 'Acupuncture'
  link: '' 
  active: true
  note: 

- id: 202 
  id_no: 20000
  category: 'Services'
  name: 'Cupping'
  link: '' 
  active: true
  note: 
  
- id: 203 
  id_no: 20000
  category: 'Services'
  name: 'Medical Massage'
  link: '' 
  active: true 
  note: 

- id: 204 
  id_no: 20000
  category: 'Services'
  name: 'Vitamins & Herbs'
  link: '' 
  active: true
  note: 

- id: 205 
  id_no: 20000
  category: 'Services'
  name: 'Homeopathics'
  link: '' 
  active: true
  note: 
  
- id: 206 
  id_no: 20000
  category: 'Services'
  name: 'Neutrition & Diet'
  link: '' 
  active: true 
  note: 
 
- id: 300 
  id_no: 10000
  category: 'Services'
  name: 'Conditions'
  link: '' 
  active: true
  note: 

- id: 301 
  id_no: 10000
  category: 'Conditions'
  name: 'Acute & Chronic Pain'
  link: '' 
  active: true
  note:

- id: 302 
  id_no: 10000
  category: 'Conditions'
  name: 'Neurology Disorder'
  link: '' 
  active: true
  note:

- id: 303 
  id_no: 10000
  category: 'Conditions'
  name: 'Emotional Disorder'
  link: '' 
  active: true
  note:

- id: 304 
  id_no: 10000
  category: 'Conditions'
  name: 'Autoimmune'
  link: '' 
  active: true
  note:

- id: 305 
  id_no: 10000
  category: 300 
  name: 'Oncology Supportive Care'
  link: '' 
  active: true
  note:

- id: 306 
  id_no: 10000
  category: 300 
  name: 'Diabetic Care'
  link: '' 
  active: true
  note:




- id: 400 
  id_no: 10000
  category:
  name: 'Patient Resources'
  link: '' 
  active: true
  note: 

- id: 500 
  id_no: 10000
  category: 
  name: 'Q & A'
  link: '' 
  active: false
  note: 

- id: 600 
  id_no: 10000
  category: 
  name: 'Appointments'
  link: '' 
  active: false
  note: 

- id: 700 
  id_no: 10000
  category: 0
  name: 'About us'
  link: '' 
  active: true
  note: 

- id: 701 
  id_no: 10000
  category: 'About us' 
  name: 'Meet us'
  link: '' 
  active: true
  note: 

- id: 702 
  id_no: 10000
  category: 'About us' 
  name: 'Testimonials'
  link: '' 
  active: true
  note: 

- id: 703 
  id_no: 10000
  category: 'About us' 
  name: 'Business Hours & Location'
  link: '' 
  active: true
  note: 

